export interface SymbolEntry {
  command: string;
  display: string;
  name: string;
}

export interface SymbolCategory {
  name: string;
  symbols: SymbolEntry[];
}

export const symbolCategories: SymbolCategory[] = [
  {
    name: 'Greek',
    symbols: [
      { command: '\\alpha', display: 'α', name: 'alpha' },
      { command: '\\beta', display: 'β', name: 'beta' },
      { command: '\\gamma', display: 'γ', name: 'gamma' },
      { command: '\\delta', display: 'δ', name: 'delta' },
      { command: '\\epsilon', display: 'ϵ', name: 'epsilon' },
      { command: '\\varepsilon', display: 'ε', name: 'varepsilon' },
      { command: '\\zeta', display: 'ζ', name: 'zeta' },
      { command: '\\eta', display: 'η', name: 'eta' },
      { command: '\\theta', display: 'θ', name: 'theta' },
      { command: '\\iota', display: 'ι', name: 'iota' },
      { command: '\\kappa', display: 'κ', name: 'kappa' },
      { command: '\\lambda', display: 'λ', name: 'lambda' },
      { command: '\\mu', display: 'μ', name: 'mu' },
      { command: '\\nu', display: 'ν', name: 'nu' },
      { command: '\\xi', display: 'ξ', name: 'xi' },
      { command: '\\pi', display: 'π', name: 'pi' },
      { command: '\\rho', display: 'ρ', name: 'rho' },
      { command: '\\sigma', display: 'σ', name: 'sigma' },
      { command: '\\tau', display: 'τ', name: 'tau' },
      { command: '\\upsilon', display: 'υ', name: 'upsilon' },
      { command: '\\phi', display: 'ϕ', name: 'phi' },
      { command: '\\varphi', display: 'φ', name: 'varphi' },
      { command: '\\chi', display: 'χ', name: 'chi' },
      { command: '\\psi', display: 'ψ', name: 'psi' },
      { command: '\\omega', display: 'ω', name: 'omega' },
      { command: '\\Gamma', display: 'Γ', name: 'Gamma' },
      { command: '\\Delta', display: 'Δ', name: 'Delta' },
      { command: '\\Theta', display: 'Θ', name: 'Theta' },
      { command: '\\Lambda', display: 'Λ', name: 'Lambda' },
      { command: '\\Xi', display: 'Ξ', name: 'Xi' },
      { command: '\\Pi', display: 'Π', name: 'Pi' },
      { command: '\\Sigma', display: 'Σ', name: 'Sigma' },
      { command: '\\Phi', display: 'Φ', name: 'Phi' },
      { command: '\\Psi', display: 'Ψ', name: 'Psi' },
      { command: '\\Omega', display: 'Ω', name: 'Omega' },
    ],
  },
  {
    name: 'Operators',
    symbols: [
      { command: '\\sum', display: '∑', name: 'sum' },
      { command: '\\prod', display: '∏', name: 'product' },
      { command: '\\int', display: '∫', name: 'integral' },
      { command: '\\oint', display: '∮', name: 'contour integral' },
      { command: '\\partial', display: '∂', name: 'partial' },
      { command: '\\nabla', display: '∇', name: 'nabla gradient' },
      { command: '\\pm', display: '±', name: 'plus minus' },
      { command: '\\mp', display: '∓', name: 'minus plus' },
      { command: '\\times', display: '×', name: 'times cross' },
      { command: '\\div', display: '÷', name: 'divide' },
      { command: '\\cdot', display: '·', name: 'center dot' },
      { command: '\\circ', display: '∘', name: 'circle compose' },
      { command: '\\infty', display: '∞', name: 'infinity' },
      { command: '\\approx', display: '≈', name: 'approximately' },
      { command: '\\neq', display: '≠', name: 'not equal' },
      { command: '\\leq', display: '≤', name: 'less equal' },
      { command: '\\geq', display: '≥', name: 'greater equal' },
      { command: '\\ll', display: '≪', name: 'much less' },
      { command: '\\gg', display: '≫', name: 'much greater' },
      { command: '\\in', display: '∈', name: 'element in' },
      { command: '\\notin', display: '∉', name: 'not element' },
      { command: '\\subset', display: '⊂', name: 'subset' },
      { command: '\\supset', display: '⊃', name: 'superset' },
      { command: '\\subseteq', display: '⊆', name: 'subset equal' },
      { command: '\\supseteq', display: '⊇', name: 'superset equal' },
      { command: '\\cup', display: '∪', name: 'union cup' },
      { command: '\\cap', display: '∩', name: 'intersection cap' },
      { command: '\\forall', display: '∀', name: 'for all' },
      { command: '\\exists', display: '∃', name: 'exists' },
      { command: '\\neg', display: '¬', name: 'negation not' },
      { command: '\\wedge', display: '∧', name: 'wedge and' },
      { command: '\\vee', display: '∨', name: 'vee or' },
      { command: '\\oplus', display: '⊕', name: 'direct sum oplus' },
      { command: '\\otimes', display: '⊗', name: 'tensor product otimes' },
    ],
  },
  {
    name: 'Arrows',
    symbols: [
      { command: '\\rightarrow', display: '→', name: 'right arrow' },
      { command: '\\leftarrow', display: '←', name: 'left arrow' },
      { command: '\\leftrightarrow', display: '↔', name: 'left right arrow' },
      { command: '\\Rightarrow', display: '⇒', name: 'double right arrow implies' },
      { command: '\\Leftarrow', display: '⇐', name: 'double left arrow' },
      { command: '\\Leftrightarrow', display: '⇔', name: 'double left right arrow iff' },
      { command: '\\uparrow', display: '↑', name: 'up arrow' },
      { command: '\\downarrow', display: '↓', name: 'down arrow' },
      { command: '\\mapsto', display: '↦', name: 'maps to' },
      { command: '\\hookrightarrow', display: '↪', name: 'hook right arrow' },
      { command: '\\hookleftarrow', display: '↩', name: 'hook left arrow' },
      { command: '\\nearrow', display: '↗', name: 'northeast arrow' },
      { command: '\\searrow', display: '↘', name: 'southeast arrow' },
      { command: '\\to', display: '→', name: 'to' },
      { command: '\\longmapsto', display: '⟼', name: 'long maps to' },
    ],
  },
  {
    name: 'Accents',
    symbols: [
      { command: '\\hat{x}', display: 'x\u0302', name: 'hat' },
      { command: '\\bar{x}', display: 'x\u0304', name: 'bar overline' },
      { command: '\\dot{x}', display: 'x\u0307', name: 'dot' },
      { command: '\\ddot{x}', display: 'x\u0308', name: 'double dot' },
      { command: '\\tilde{x}', display: 'x\u0303', name: 'tilde' },
      { command: '\\vec{x}', display: 'x\u20D7', name: 'vector' },
      { command: '\\overline{x}', display: 'x\u0305', name: 'overline' },
      { command: '\\underline{x}', display: 'x\u0332', name: 'underline' },
      { command: '\\widehat{x}', display: 'x\u0302', name: 'wide hat' },
      { command: '\\widetilde{x}', display: 'x\u0303', name: 'wide tilde' },
    ],
  },
  {
    name: 'Delimiters',
    symbols: [
      { command: '\\langle', display: '⟨', name: 'left angle bracket' },
      { command: '\\rangle', display: '⟩', name: 'right angle bracket' },
      { command: '\\lfloor', display: '⌊', name: 'left floor' },
      { command: '\\rfloor', display: '⌋', name: 'right floor' },
      { command: '\\lceil', display: '⌈', name: 'left ceiling' },
      { command: '\\rceil', display: '⌉', name: 'right ceiling' },
      { command: '\\lVert', display: '‖', name: 'left double bar norm' },
      { command: '\\rVert', display: '‖', name: 'right double bar norm' },
      { command: '\\{', display: '{', name: 'left brace' },
      { command: '\\}', display: '}', name: 'right brace' },
      { command: '\\lbrack', display: '[', name: 'left bracket' },
      { command: '\\rbrack', display: ']', name: 'right bracket' },
    ],
  },
];
